### ISSUE TITLE
Which folder should TodosContainer.js be in?

### ISSUE THREAD

**Issue by justinmcdavid** [SF-WDI-LABS/react-todo-walkthrough-jquery#1]
The instructions state first that it should be in the containers folder, and then later that it should be in the components folder.
![screen shot 2017-06-11 at 9 03 08 pm](https://user-images.githubusercontent.com/12969375/27019032-b7787750-4ee9-11e7-9e12-423583024846.png)
![screen shot 2017-06-11 at 9 00 46 pm](https://user-images.githubusercontent.com/12969375/27019034-b98f0c20-4ee9-11e7-8cb8-4c2107031448.png)

**Comment by mnfmnfm** [comment]
Thanks, Justin! Fixed now.
